import = [
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 162, lines = 40 }

[font]
normal = { family = "IntoneMonoNerdFont", style = "Regular" }

[env]
TERM = "xterm-256color"
